# Radio Contest Winner Configuration Example
# Copy this file to config.yaml and modify as needed

# Audio stream configuration
stream:
  url: "https://ais-sa1.streamon.fm:443/7346_48k.aac"

# Whisper transcription model configuration
whisper:
  model_path: "./models/ggml-base.en.bin"

# Context buffer configuration
buffer:
  # Buffer duration in milliseconds (1000-10000 allowed, default: 2500)
  # This controls how long segments are buffered before being combined
  # into more coherent sentences for contest parsing
  duration_ms: 2500