# Radio Contest Winner Configuration Example
# Copy this file to config.yaml and modify as needed

# Audio stream configuration
stream:
  url: "https://ais-sa1.streamon.fm:443/7346_48k.aac"

# Whisper transcription model configuration
whisper:
  model_path: "./models/ggml-base.en.bin"

# Context buffer configuration
buffer:
  # Buffer duration in milliseconds (1000-10000 allowed, default: 2500)
  # This controls how long segments are buffered before being combined
  # into more coherent sentences for contest parsing
  duration_ms: 2500

# Number allowlist configuration for contest parsing
allowlist:
  # List of numbers to filter for in transcription text
  # Only transcription segments containing these numbers will be processed
  # for contest information. This helps filter out commercials and irrelevant chatter.
  # Examples: ham radio call signs, contest numbers, frequency allocations
  numbers:
    - "73"       # Common ham radio sign-off
    - "146"      # 2-meter band frequency
    - "222"      # 220 MHz band
    - "0146"     # Frequency with leading zero
    # Add more numbers as needed for your contest

# Debug mode configuration
debug_mode: false
# When enabled, all transcribed audio segments are printed to console
# with timestamps, confidence scores, and timing information
# This is useful for monitoring transcription quality and debugging
# Can be toggled at runtime without restarting the application